### ISSUE TITLE
No py4j dependency

### ISSUE THREAD

**Issue by quartox** [dask/old-dask-yarn#12]
I tried `conda install -c dask dask-yarn` and got an import error for `py4j` (which I found in the blaze channel).

**Comment by mrocklin** [comment]
Glad to see you again @quartox !  @quasiben and I were just talking about you an hour ago actually and about making this process somewhat smoother and publishing a quick how-to guide as a blogpost.

Are you available as a guinea pig to test things out near-term?

**Comment by quartox** [comment]
Absolutely!

**Comment by quasiben** [comment]
fixing tonight

**Comment by quasiben** [comment]
PR https://github.com/dask/knit/pull/63 fixes this issue.  I'll release shortly after i get through the other issues you filed closed.  Oh, I also added py3.6 and removed py2.6 builds
