### ISSUE TITLE
specifying nn and rm does not stop autodetect

### ISSUE THREAD

**Issue by perryhook** [dask/old-dask-yarn#9]
I'm not sure if this behavior is the desired one or not, but simply specifying `nn`, `nn_port`, `rm`, or `rm_port` does not pass this along to Knit. I'm guessing this is not desired b/c of the comment. Starting at line 47 in `core.py`:
```
# if any hdfs/yarn settings are used don't use autodetect
if autodetect or not any([nn, nn_port, rm, rm_port]):
    self.knit = Knit(autodetect=True, validate=validate)
```

which ignores the settings unless the default `True` value for `autodetect` is overridden.
I found it very confusing that simply passing the nn and rm args were not enough to have those pass through to Knit, but I also had to add `autodetect=False`.

Is this the desired behavior or a bug?

**Comment by quasiben** [comment]
This is a bug.  The intended behavior is as the comment states.  I'll submit a PR to fix.  Thanks!
